### ISSUE TITLE
Floor set to x.5 causes range slider to continually update

### ISSUE THREAD

**Issue by goldenram** [angular-slider/angularjs-slider#316] opened 2016-04-15 12:51 UTC
Using the Angular Slider all options demo you can reproduce this, set all the values to integers and notice the slider behaves as expected.  Now change the floor to, say, 5.5.  Notice that both the min and max values continually update by a step of 2.  The strange part is only "x.5" causes this issue.  If you set the floor to 5.4, no problem.  If you set the floor to 5.6 no problem.  I tested 5.0 - 5.9 and only 5.5 makes the slider values continually update.

**Comment by ValentinH** [comment] 2016-04-15 14:29
Do you have an example different that the "All options demo"? Because this demo is not really mainstream and I can't reproduce your bug in a single slider...

**Comment by goldenram** [comment] 2016-04-15 14:31
Hmm, so a single range slider does not do it?  I will have to try that, on my product there are multiple sliders on a page.

**Comment by ValentinH** [comment] 2016-04-15 14:44
What I mean is that it would be much easier for me to fix it if you can create the simpliest demo reproducing the problem so I can understand it easier.

**Comment by goldenram** [comment] 2016-04-15 15:09
OK, got it on a single slider:  https://jsfiddle.net/hmz8vqd2/1/.  Change floor to 5.5 and you should see it moving.

**Comment by ValentinH** [comment] 2016-04-15 15:45
Thanks. For now, you can set `precision` to 1, it will fix the problem.

**Comment by goldenram** [comment] 2016-04-15 16:14
Thanks Valentin!

**Comment by ValentinH** [comment] 2016-05-19 11:22
I'm closing this issue since simply setting the precision fix it. Indeed, precision should always been used when using floating values.

**Closed by ValentinH** 2016-05-19 11:22 UTC
Labels: bug
