### ISSUE TITLE
Overlapping max and ceil value label

### ISSUE THREAD

**Issue by aaabidunique** [angular-slider/angularjs-slider#396] opened 2016-08-12 07:22 UTC
### Steps to reproduce
1. After adding slider and set max and ceil value.
2. force render before actually showing to user.
   Note:  I am using this plugin in ionic app.
### Expected behaviour

It should show floor  and  min value with same label and max and ceil with same label.
### Actual behaviour

Max value and ceil value shows overlapping label with same value.
![screenshot_20160812-125112](https://cloud.githubusercontent.com/assets/9800757/17615377/8e98c72e-608b-11e6-883f-394f73234041.jpg)

**Comment by ValentinH** [comment] 2016-08-12 07:25
Does it only occur with vertical sliders? Could you set up a demo reproducing the issue please?

**Comment by aaabidunique** [comment] 2016-08-12 09:32
Haven't tried but i think yes.
I tried to  mock the same way i am doing on app and got the same result in the end.

http://jsfiddle.net/cwhgLcjv/113/

**Comment by ValentinH** [comment] 2016-08-12 11:17
Indeed, this is a bug that only occurs with vertical sliders. However, your issue is due to the fact that you instantiate your slider value without model/high values...

**Comment by aaabidunique** [comment] 2016-08-12 11:35
Actually i am providing these value at the time of Initialization but could do the same for the example.
Hope it will be fixed in next build or any quick fix.
FYI i am assigning those value at Initialization.

**Comment by ValentinH** [comment] 2016-08-12 11:36
Are you sure that when the slider becomes visible, it's values are correctly initialized?

**Comment by aaabidunique** [comment] 2016-08-12 11:41
Actually values are there when it become visible because i can see but doesn't show properly, so ineed to use
$timeout(function () {
        $scope.$broadcast('rzSliderForceRender');
    });
for force render then its appear as above image.

**Comment by aaabidunique** [comment] 2016-09-23 09:18
@ValentinH any update on this bug.

**Comment by ValentinH** [comment] 2016-09-23 09:45
No, I don't have much time to spend on this project currently.

 It would be easier to investigate it i you could provide a demo of the bug with correctly initialized value on start.

**Comment by costea93** [comment] 2016-10-11 06:34
Also this bug persist on vertical sliders!

**Comment by ValentinH** [comment] 2016-10-11 06:36
@costea93 do you have a demo reproducing this bug?

**Comment by costea93** [comment] 2016-10-11 06:42
<img width="305" alt="screen shot 2016-10-11 at 09 32 15" src="https://cloud.githubusercontent.com/assets/7778335/19260918/4dc46444-8f96-11e6-8d47-ad9fc2c6d208.png">
unfortunately, i can't show here some code from project.

**Comment by ValentinH** [comment] 2016-10-11 06:48
Unfortunately, if I don't have any code, I can't reproduce and understand easily the bug.
Thus, 2 solutions:
- you can provide a minimal reproducing demo that only shows slider specific code.
- you try to understand to library code, find a way to fix your issue and submit a pull request.

**Comment by costea93** [comment] 2016-10-11 06:54
@ValentinH the problem is here: 
<span class="rz-bubble rz-limit rz-ceil"></span> 
because initially this span needs to be hidden, at the moment this span has style: visibility: visible;

**Comment by ValentinH** [comment] 2016-10-11 07:23
Yes but it should be hidden during initialization: https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L692

**Comment by ValentinH** [comment] 2016-10-11 07:26
The function responsible for showing/hiding labels is this one: https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L1124

**Comment by costea93** [comment] 2016-10-11 09:11
i can't change library to see what will be happened after my changes because we use rzslider as bower component. :(

I don't know why first span have visibility **hidden** and second **visible**

`<span class="rz-bubble rz-limit rz-floor" style="visibility: hidden; left: 0px;">1000</span>`
`<span class="rz-bubble rz-limit rz-ceil" style="visibility: visible; left: 362.641px;">2000</span>`

And one intresting thing here - this problem disappear after screen resize.

**Comment by ValentinH** [comment] 2016-10-11 09:16
Actually, you can edit even with Bower. You just need to locate the rzslider.js file in the bower folder and directly edit it.

**Comment by costea93** [comment] 2016-10-11 10:01
The problem is here:

`if (isMinLabAtCeil) {
          clHidden = true;
          this.hideEl(this.ceilLab);
        } else {
          clHidden = false;
          this.showEl(this.ceilLab);
        }`
because when page was loaded if condition is executed and everything is ok. But i have one click event and do that in this event to rerender slider:
`$timeout(function () {
        $scope.$broadcast('rzSliderForceRender');
      }, 100);`
after that executed condition is else because isMinLabAtCeil === false

do you have any ideas, how can i resolve that?

**Comment by ValentinH** [comment] 2016-10-13 06:37
It is a weird behavior, I really need to see a demo of it...

**Comment by ValentinH** [comment] 2016-10-22 16:21
@costea93 in your slider options, do you set `floor` and `ceil`?

**Comment by ValentinH** [comment] 2016-11-05 11:50
I finally managed to reproduce it and fix it. Released with 5.8.5

**Closed** 2016-11-05 11:50 UTC
Labels: bug

**Comment by ValentinH** [comment] 2018-08-14 10:47
Again, please provide a demo showing the bug.

**Comment by vkshriva** [comment] 2018-08-15 16:41
Thanks, Valentin for a quick response.

I'll share the same as the application is big, I'll be back soon. Meanwhile, let me share whatever I am facing the issue theoretically

 

Case1: When I am using version 6.6.0,  while first time rendering of a page  slider will look like as below

and **restrictedRange** property will work fine

 
![slidder](https://user-images.githubusercontent.com/27609552/44160452-132e9480-a0d8-11e8-85bf-0016b7229b15.PNG)


Case2: When I am using version 5.8.5 while  rendering of a page  slider will work fine but  **restrictedRange**  will  not work
![slidderhappy](https://user-images.githubusercontent.com/27609552/44160464-1a55a280-a0d8-11e8-8134-3e5f3168c41e.png)
