### ISSUE TITLE
Range one problem

### ISSUE THREAD

**Issue by abhyaasa** [angular-slider/angularjs-slider#300] opened 2016-03-22 22:47 UTC
![screen shot 2016-03-22 at 6 25 49 pm](https://cloud.githubusercontent.com/assets/10455341/13970008/815e12ca-f05c-11e5-9518-3611c7c20107.png)

### Steps to reproduce
1. Setup a range slider with min and floor at 0 and max and ceil at 1. Any two consecutive integers might have the same problem, but haven't confirmed that. 0 and 1 is the scenario that sometimes occurs naturally in my application.
2. The problem is intermittent, and I haven't found what it takes to replicate it. I fiddled with it while running my demo fiddle (linked below) and it happened: see attached screen shot. In my app it was consistently happening when the app loaded, and sometimes thereafter.
3. As an awkward work-around, when min and max are 0 and 1, and not otherwise, I set step to 0.5 and precision to 1.

Demo: https://jsfiddle.net/vasudeva_chaynes/fmuzeu0v/2/

### Expected behavior
Low and high markers at opposite ends of bar with 0 and 1 above, resp.

### Actual behavior
Low and high markers superimposed at left, with "0 - 1" text above.

### PS
Thanks for a generally-great library contribution!

**Comment by ValentinH** [comment] 2016-03-23 06:50
Indeed this is a pretty weird behavior and I couldn't reproduce either. What browser are you using?

**Comment by abhyaasa** [comment] 2016-03-23 13:55
jsfiddle was using Safari. I've seen the problem testing my ionic app in desktop server mode using Chrome, and on iPhone.

**Comment by zppro** [comment] 2016-05-04 03:30
$timeout(function () {
            $scope.$broadcast('rzSliderForceRender');
});
try this in your controller.
by the way,

**Comment by abhyaasa** [comment] 2016-05-04 11:42
That seems to have fixed it. Thanks!

**Comment by abhyaasa** [comment] 2016-05-04 11:58
Umm, it helps sometimes, not resolved.

**Comment by ValentinH** [comment] 2016-05-19 11:19
I'm closing this one since I can't reproduce it.

**Closed by ValentinH** 2016-05-19 11:19 UTC
Labels: bug
